services:
  dashkey:
    image: rafaelmeirim/dashkey:latest
    container_name: dashkey
    restart: unless-stopped
    ports:
      - "3080:80"  # change 3080 to any available port on your host
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js:ro
      - ./data/links.js:/usr/share/nginx/html/data/links.js:ro
      - ./images:/usr/share/nginx/html/images:ro
      - ./icons:/usr/share/nginx/html/icons:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
